UPM/mysite/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from musicup import views

urlpatterns = [
    path('', views.home, name='home'),
    path('upload/', views.upload, name='upload'),
    path('delete/<int:pk>/', views.delete_music, name='delete_music'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UPM/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

UPM/musicup/models.py
from django.db import models

class Music(models.Model):
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    audio_file = models.FileField(upload_to='musics/')
    thumbnail = models.ImageField(upload_to='thumbnails/', null=True, blank=True)
    summary = models.TextField(null=True, blank=True)


    class Meta:
        app_label = 'musicup'

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.audio_file.delete()
        super().delete(*args, **kwargs)

UPM/musicup/forms.py
from django import forms
from .models import Music

class MusicForm(forms.ModelForm):
    class Meta:
        model = Music
        fields = ('title', 'artist', 'audio_file', 'summary')
        

UPM/musicup/views.py
from django.shortcuts import render, redirect
from .forms import MusicForm
from .models import Music
from django.shortcuts import get_object_or_404

def home(request):
    musics = Music.objects.all()
    return render(request, 'musicup/home.html', {'musics': musics})

def upload(request):
    if request.method == 'POST':
        form = MusicForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = MusicForm()
    return render(request, 'musicup/upload.html', {'form': form})

def delete_music(request, pk):
    music = get_object_or_404(Music, pk=pk)
    if request.method == 'POST':
        music.delete()
        return redirect('home')
    return render(request, 'musicup/delete_music.html', {'music': music})

UPM/musicup/templates/musicup/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'upload' %}">Upload</a></li>
        </ul>
    </nav>
    <main>
        {% block main_content %}{% endblock %}
    </main>
    {% block extra_content %}{% endblock %}
</body>
</html>

UPM/musicup/templates/musicup/home.html
<!-- templates/home.html -->
{% extends 'musicup/base.html' %}

{% block main_content %}
  <h1>Music</h1>
  <ul>
    {% for music in musics %}
        <li>
            {{ music.title }} by {{ music.artist }}
            <img src="{{ music.thumbnail.url }}" alt="{{ music.title }}" width="100">
            <p>{{ music.summary }}</p>
            <audio controls src="{{ music.audio_file.url }}">Your browser does not support the audio element.
            </audio>
            <form method="post" action="{% url 'delete_music' music.pk %}" style="display: inline">
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
        </li>
    {% endfor %}
  </ul>
{% endblock %}

UPM/musicup/templates/musicup/upload.html
<!-- templates/upload.html -->
{% extends 'musicup/base.html' %}

{% block main_content %}
  <h1>Upload Music</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="id_thumbnail">Thumbnail:</label>
    <input type="file" name="thumbnail" id="id_thumbnail">
    <button type="submit">Upload</button>
  </form>
{% endblock %}